// Generated by: npx supabase gen types typescript --project-id $SUPABASE_PROJECT_ID --schema public
// Run after every migration to regenerate.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string
          name: string
          slug: string
          logo_url: string | null
          status: 'trial' | 'active' | 'suspended'
          plan: 'starter' | 'growth' | 'enterprise'
          settings: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          logo_url?: string | null
          status?: 'trial' | 'active' | 'suspended'
          plan?: 'starter' | 'growth' | 'enterprise'
          settings?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          logo_url?: string | null
          status?: 'trial' | 'active' | 'suspended'
          plan?: 'starter' | 'growth' | 'enterprise'
          settings?: Json
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      users: {
        Row: {
          id: string
          tenant_id: string | null
          role: 'SUPER_ADMIN' | 'TENANT_ADMIN' | 'MANAGER' | 'DRIVER' | 'CUSTOMER'
          first_name: string | null
          last_name: string | null
          phone: string | null
          is_active: boolean
          created_at: string
        }
        Insert: {
          id: string
          tenant_id?: string | null
          role: 'SUPER_ADMIN' | 'TENANT_ADMIN' | 'MANAGER' | 'DRIVER' | 'CUSTOMER'
          first_name?: string | null
          last_name?: string | null
          phone?: string | null
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string | null
          role?: 'SUPER_ADMIN' | 'TENANT_ADMIN' | 'MANAGER' | 'DRIVER' | 'CUSTOMER'
          first_name?: string | null
          last_name?: string | null
          phone?: string | null
          is_active?: boolean
          created_at?: string
        }
        Relationships: []
      }
      products: {
        Row: {
          id: string
          tenant_id: string
          name_en: string
          name_ne: string
          sku: string | null
          category: 'JAR_20L' | 'JAR_10L' | 'JAR_5L' | 'CUSTOM' | null
          price_b2c: number
          price_b2b: number
          deposit_amount: number
          reorder_level: number
          is_active: boolean
          image_url: string | null
          created_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          name_en: string
          name_ne: string
          sku?: string | null
          category?: 'JAR_20L' | 'JAR_10L' | 'JAR_5L' | 'CUSTOM' | null
          price_b2c: number
          price_b2b: number
          deposit_amount?: number
          reorder_level?: number
          is_active?: boolean
          image_url?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          name_en?: string
          name_ne?: string
          sku?: string | null
          category?: 'JAR_20L' | 'JAR_10L' | 'JAR_5L' | 'CUSTOM' | null
          price_b2c?: number
          price_b2b?: number
          deposit_amount?: number
          reorder_level?: number
          is_active?: boolean
          image_url?: string | null
          created_at?: string
        }
        Relationships: []
      }
      inventory_ledger: {
        Row: {
          id: string
          tenant_id: string
          product_id: string
          type: 'IN' | 'OUT' | 'ADJUSTMENT' | 'RETURN_EMPTY' | 'TRANSFER'
          quantity: number
          balance_before: number
          balance_after: number
          reference_id: string | null
          reference_type: 'order' | 'purchase_order' | 'manual' | null
          note: string | null
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          product_id: string
          type: 'IN' | 'OUT' | 'ADJUSTMENT' | 'RETURN_EMPTY' | 'TRANSFER'
          quantity: number
          balance_before: number
          balance_after: number
          reference_id?: string | null
          reference_type?: 'order' | 'purchase_order' | 'manual' | null
          note?: string | null
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          product_id?: string
          type?: 'IN' | 'OUT' | 'ADJUSTMENT' | 'RETURN_EMPTY' | 'TRANSFER'
          quantity?: number
          balance_before?: number
          balance_after?: number
          reference_id?: string | null
          reference_type?: 'order' | 'purchase_order' | 'manual' | null
          note?: string | null
          created_by?: string | null
          created_at?: string
        }
        Relationships: []
      }
      customers: {
        Row: {
          id: string
          tenant_id: string
          user_id: string | null
          type: 'B2C' | 'B2B'
          name: string
          phone: string | null
          email: string | null
          address: Json | null
          credit_limit: number
          credit_terms: 'net30' | 'net60' | 'net90' | null
          notes: string | null
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          user_id?: string | null
          type?: 'B2C' | 'B2B'
          name: string
          phone?: string | null
          email?: string | null
          address?: Json | null
          credit_limit?: number
          credit_terms?: 'net30' | 'net60' | 'net90' | null
          notes?: string | null
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          user_id?: string | null
          type?: 'B2C' | 'B2B'
          name?: string
          phone?: string | null
          email?: string | null
          address?: Json | null
          credit_limit?: number
          credit_terms?: 'net30' | 'net60' | 'net90' | null
          notes?: string | null
          is_active?: boolean
          created_at?: string
        }
        Relationships: []
      }
      orders: {
        Row: {
          id: string
          tenant_id: string
          order_number: string
          customer_id: string
          type: 'B2C' | 'B2B'
          status: 'DRAFT' | 'CONFIRMED' | 'ASSIGNED' | 'OUT_FOR_DELIVERY' | 'DELIVERED' | 'FAILED' | 'CANCELLED'
          assigned_driver_id: string | null
          scheduled_date: string | null
          delivery_address: Json | null
          payment_method: 'CASH' | 'ESEWA' | 'KHALTI' | 'CREDIT' | null
          payment_status: 'PENDING' | 'PARTIAL' | 'PAID'
          subtotal: number
          vat_amount: number
          total: number
          empties_collected: number
          delivery_photo_url: string | null
          notes: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          order_number: string
          customer_id: string
          type: 'B2C' | 'B2B'
          status?: 'DRAFT' | 'CONFIRMED' | 'ASSIGNED' | 'OUT_FOR_DELIVERY' | 'DELIVERED' | 'FAILED' | 'CANCELLED'
          assigned_driver_id?: string | null
          scheduled_date?: string | null
          delivery_address?: Json | null
          payment_method?: 'CASH' | 'ESEWA' | 'KHALTI' | 'CREDIT' | null
          payment_status?: 'PENDING' | 'PARTIAL' | 'PAID'
          subtotal?: number
          vat_amount?: number
          total?: number
          empties_collected?: number
          delivery_photo_url?: string | null
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          order_number?: string
          customer_id?: string
          type?: 'B2C' | 'B2B'
          status?: 'DRAFT' | 'CONFIRMED' | 'ASSIGNED' | 'OUT_FOR_DELIVERY' | 'DELIVERED' | 'FAILED' | 'CANCELLED'
          assigned_driver_id?: string | null
          scheduled_date?: string | null
          delivery_address?: Json | null
          payment_method?: 'CASH' | 'ESEWA' | 'KHALTI' | 'CREDIT' | null
          payment_status?: 'PENDING' | 'PARTIAL' | 'PAID'
          subtotal?: number
          vat_amount?: number
          total?: number
          empties_collected?: number
          delivery_photo_url?: string | null
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      order_items: {
        Row: {
          id: string
          order_id: string
          tenant_id: string
          product_id: string
          quantity: number
          unit_price: number
          deposit_amount: number
          subtotal: number
        }
        Insert: {
          id?: string
          order_id: string
          tenant_id: string
          product_id: string
          quantity: number
          unit_price: number
          deposit_amount?: number
          subtotal: number
        }
        Update: {
          id?: string
          order_id?: string
          tenant_id?: string
          product_id?: string
          quantity?: number
          unit_price?: number
          deposit_amount?: number
          subtotal?: number
        }
        Relationships: []
      }
      order_sequences: {
        Row: {
          tenant_id: string
          date_key: string
          last_seq: number
        }
        Insert: {
          tenant_id: string
          date_key: string
          last_seq?: number
        }
        Update: {
          tenant_id?: string
          date_key?: string
          last_seq?: number
        }
        Relationships: []
      }
      invoices: {
        Row: {
          id: string
          tenant_id: string
          invoice_number: string
          order_id: string | null
          customer_id: string
          status: 'DRAFT' | 'SENT' | 'PAID' | 'OVERDUE' | 'CANCELLED'
          subtotal: number
          vat_rate: number
          vat_amount: number
          total: number
          due_date: string | null
          paid_at: string | null
          payment_method: 'CASH' | 'ESEWA' | 'KHALTI' | 'CREDIT' | null
          pdf_url: string | null
          bs_date: string | null
          created_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          invoice_number: string
          order_id?: string | null
          customer_id: string
          status?: 'DRAFT' | 'SENT' | 'PAID' | 'OVERDUE' | 'CANCELLED'
          subtotal: number
          vat_rate?: number
          vat_amount: number
          total: number
          due_date?: string | null
          paid_at?: string | null
          payment_method?: 'CASH' | 'ESEWA' | 'KHALTI' | 'CREDIT' | null
          pdf_url?: string | null
          bs_date?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          invoice_number?: string
          order_id?: string | null
          customer_id?: string
          status?: 'DRAFT' | 'SENT' | 'PAID' | 'OVERDUE' | 'CANCELLED'
          subtotal?: number
          vat_rate?: number
          vat_amount?: number
          total?: number
          due_date?: string | null
          paid_at?: string | null
          payment_method?: 'CASH' | 'ESEWA' | 'KHALTI' | 'CREDIT' | null
          pdf_url?: string | null
          bs_date?: string | null
          created_at?: string
        }
        Relationships: []
      }
      invoice_sequences: {
        Row: {
          tenant_id: string
          fiscal_year_key: string
          last_seq: number
        }
        Insert: {
          tenant_id: string
          fiscal_year_key: string
          last_seq?: number
        }
        Update: {
          tenant_id?: string
          fiscal_year_key?: string
          last_seq?: number
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: {
      set_tenant_context: {
        Args: { p_tenant_id: string }
        Returns: void
      }
      increment_order_sequence: {
        Args: { p_tenant_id: string; p_date_key: string }
        Returns: number
      }
      increment_invoice_sequence: {
        Args: { p_tenant_id: string; p_fiscal_year_key: string }
        Returns: number
      }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
